### ISSUE TITLE
CUDA out of memory. 

### ISSUE THREAD

**Issue by yarqian** [IDKiro/CBDNet-pytorch#14]
Hi, 
   I just run the test code, but get the error. 
RuntimeError: CUDA out of memory. Tried to allocate 3.83 GiB (GPU 0; 23.65 GiB total capacity; 16.60 GiB already allocated; 3.37 GiB free; 1.09 GiB cached)
And then I just try to use the train code, It is ok. 
would you please help me for this problem?

**Comment by IDKiro** [comment]
Train code use cropped small images as input, but test code use full size images. 24GB gpu memory is still not enough. Just crop the input images or use cpu when test.

**Comment by IDKiro** [comment]
i'll close the issue
