### ISSUE TITLE
预训练的模型，似乎没有效果吗？

### ISSUE THREAD

**Issue by geyijun** [IDKiro/CBDNet-pytorch#15]
你好，
       从百度网盘上下载预训练模型，放入checkpoint。把要去找的图片放入对应位置。
python ./test.py --ckpt synthetic 
     从输出的图片看,似乎没有任何的去噪效果呀？

**Comment by IDKiro** [comment]
这是正常的，两个原因：
PSNR和你人眼看的不一样，虽然看上去输出图还是有很多的噪点，其实PSNR是明显上升了的；
噪声模型实现有一定的问题，不过官方的python实现也和他们matlab的代码不一样，他们自己的python代码可能是借鉴UIP的。
你有兴趣的话可以用官方的噪声模型替换这个库的模型进行训练。
