### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by YuxinZou** [IDKiro/CBDNet-pytorch#16]
你好，
请问你网盘上的预训练模型是已经用数据集训练处来的模型么？

**Comment by IDKiro** [comment]
是的，但是结果一般，PSNR比论文低一点。
想要改进可以使用官方repo中的噪声模型python代码，那个原作者根据UPI改进过，最终成绩会比论文中还要高很多。
如果还要进一步提升，那可以把renoir数据集改成sidd。
PSNR可以到39以上。
