### ISSUE TITLE
about datasets

### ISSUE THREAD

**Issue by chen-pursue** [IDKiro/CBDNet-pytorch#17]
Excuse me, I want to know the name of your real image training datasets

**Comment by IDKiro** [comment]
The dataset used in the original CBDNet:
ReNOIR：RENOIR - A Dataset for Real Low-Light Image Noise Reduction (Arxiv 2014), Anaya, Barbu.
Better dataset:
SIDD：A High-Quality Denoising Dataset for Smartphone Cameras (CVPR 2018), Abdelhamed et al.

**Comment by chen-pursue** [comment]
Thank you for answering my question, it helped me a lot.
