### ISSUE TITLE
噪声图的三个通道相同

### ISSUE THREAD

**Issue by Big-Wuu** [IDKiro/CBDNet-pytorch#19]
你好，请问网盘中所提供的SIGMA*.png为什么三个通道是相同的？按照sigma_total = np.sqrt(sigma_s * img + sigma_c)，三个通道的sigma应该是不同的啊？
另外，想问一下生成Syn_train的原数据集是什么？

谢谢！

**Comment by IDKiro** [comment]
DIV2K，超分常用数据集。
现在用的是一通道的噪声图，合成噪声图直接用了反转ISP后得到的RAW图像的噪声图，也就是实际添加的噪声。
上个版本我确实还是用的sRGB图像合成噪声图，是三通道的，因为根据我现在的经验这个5层FCN的噪声估计意义不大，所以就改成了一通道的输出直接预测。
你可以改一下合成噪声数据的代码，试一下在sRGB域上生成噪声图。

**Comment by IDKiro** [comment]
感觉还是改回3通道说得通一点，重新训练一下晚上commit一版好了

**Comment by IDKiro** [comment]
有什么问题的话可以开新issue，新的数据集在重新上传了（但是速度很慢
