### ISSUE TITLE
关于机器配置

### ISSUE THREAD

**Issue by pcl111** [IDKiro/CBDNet-pytorch#20]
我遇到了这个问题RuntimeError: Expected object of scalar type Double but got scalar type Float for sequence element 2 in sequence argument at position #1 'tensors'是因为机器得原因吗，想问一下你具体pytorch和python还有numpy的版本，非常感谢

**Comment by IDKiro** [comment]
单双浮点问题
你定位到错误的行，然后强制转换就行

你这样问我不好估计具体的问题

pytorch                   1.7.1
numpy                     1.19.2
python                    3.8.5

版本问题一般不会导致类型不同，你应该是改了代码吧

**Comment by pcl111** [comment]
已经解决了，非常感谢
