### ISSUE TITLE
noise level map

### ISSUE THREAD

**Issue by HLIG** [IDKiro/CBDNet-pytorch#21]
感谢大佬的开源，发现有个奇怪的现象，就是用预训练的模型，输出的噪声估计图为全0。具体现象为：噪声估计网络(fcn)的最后一个卷积输出全为负值，经过RELU之后，输出的噪声估计图为全零。
这意味着加的噪声水平监督对网络学习并没有什么用？

p.s.感觉加的噪声水平监督有点奇怪
`sigma_total = np.sqrt(sigma_s * img + sigma_c)  `
这里的**img** 是否应该替换成RAW图，而不是RGB图。

**Comment by IDKiro** [comment]
监督应该是在RGB上做的，这样才能表征出真实彩色图像的噪声分布在通道和空间上的不一致性，而且我记得官方代码FCN部分输出通道也是3。
至于这个现象，我自己没观察过，我简单分析下：
1. 因为训练数据集不一样，loss各部分的权重需要修改，因为FCN这时候输出全0，这样噪声图的TV loss最小，可能是这一项支配了整个训练过程；
2. 代码写错了，比较可能的是训练数据sample错了；

我觉得1比较可能吧，因为训练数据合成噪声的时候，噪声水平的取样方式变了，导致平均噪声水平比原文低，进而导致噪声水平监督这一项值变小，被其他两项支配了，导致FCN功能退化。
至于噪声水平监督有没有用，应该是有用的，你可以理解为正则作用，不过可能在训练集足够大时作用被稀释。

**Comment by IDKiro** [comment]
我没时间去排查具体的问题，所以现在更新了README作为提醒，你要是排查出问题可以pull。

**Comment by IDKiro** [comment]
你没回复，我先把issue关了，你要有问题可以重开
