### ISSUE TITLE
What is the sigma image means?

### ISSUE THREAD

**Issue by linqiaozhou** [IDKiro/CBDNet-pytorch#22]
Hello, There are imgs with prefix 'SIGMA_SRGB' in the folder 'Syn_train', and they are used as the ground truth as the FCN net.  I wonder what is meaning of the 'sigma images' and how can i generate it?

**Comment by IDKiro** [comment]
It means the noise std used in noisy image generation.
You can use codes in `utils/syn/generate_dataset.py` to generate it.
