### ISSUE TITLE
Is there a way to report Noise Variance?

### ISSUE THREAD

**Issue by MrBled** [IDKiro/CBDNet-pytorch#25]
I am experimenting with generate_dataset.py and ISP_implement.py and I am trying to return sigma_s and sigma_c to find an approximation of the noise value. I have tried doing sigma*255 and also np.sqrt(sigma)*255 but the numbers returned do not make sense for sigma_c (they are very low). 

Is there a way of finding the chosen variance for both sigma_c and sigma_s? in terms of [0-255] 

Thanks

[Marking as solved because I wasn't correctly informed when I asked the question]

**Comment by reminayano** [comment]
I solved the situation by following way. thank you.

changed `_, out_image = CBDNet(in_image)` to `noise_level, out_image = CBDNet(in_image)`
and 
changed`output = sess.run(out_image, feed_dict={in_image: temp_noisy_img})` to  `noise_level_output, output = sess.run([noise_level, out_image], feed_dict={in_image: temp_noisy_img})`
