### ISSUE TITLE
有关noise level map

### ISSUE THREAD

**Issue by scutcr7** [IDKiro/CBDNet-pytorch#3]
你好，请问在你的实现中对于groud truth的noise level map，是直接把噪声图和原始图相减了吗，但是在作者的matlab实现中是不是要复杂一些。想知道这样可以吗。

**Comment by IDKiro** [comment]
合成的数据集是会返回noise map的，但是真实数据集我只能相减，可能我没有看到这部分的实现。如果你能指出具体实现方法请告诉我，我抽空进行实现。

**Comment by scutcr7** [comment]
想问一下您有训练并且测试过在”真实”噪声图上的效果吗，使用train_real文件


------------------ 原始邮件 ------------------
发件人: "IDKiro"<notifications@github.com>;
发送时间: 2019年8月1日(星期四) 中午1:12
收件人: "IDKiro/CBDNet-pytorch"<CBDNet-pytorch@noreply.github.com>;
抄送: "C。罗纳尔多"<875713197@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [IDKiro/CBDNet-pytorch] 有关noise level map (#3)




合成的数据集是会返回noise map的，但是真实数据集我只能相减，可能我没有看到这部分的实现。如果你能指出具体实现方法请告诉我，我抽空进行实现。

**Comment by scutcr7** [comment]
还有一个问题想请教一下，“真实”噪声图不是只有噪声图吗。您通过一个噪声图和原始图的相减操作得到noise map，那么这个原始图是怎么得到的呢




------------------ 原始邮件 ------------------
发件人: "IDKiro"<notifications@github.com>;
发送时间: 2019年8月1日(星期四) 中午1:12
收件人: "IDKiro/CBDNet-pytorch"<CBDNet-pytorch@noreply.github.com>;
抄送: "C。罗纳尔多"<875713197@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [IDKiro/CBDNet-pytorch] 有关noise level map (#3)




合成的数据集是会返回noise map的，但是真实数据集我只能相减，可能我没有看到这部分的实现。如果你能指出具体实现方法请告诉我，我抽空进行实现。

**Comment by scutcr7** [comment]
还有一个问题想请教一下，“真实”噪声图不是只有噪声图吗。您通过一个噪声图和原始图的相减操作得到noise map，那么这个原始图是怎么得到的呢
###############################
是从HR图下采样吗？




------------------ 原始邮件 ------------------
发件人: "IDKiro"<notifications@github.com>;
发送时间: 2019年8月1日(星期四) 中午1:12
收件人: "IDKiro/CBDNet-pytorch"<CBDNet-pytorch@noreply.github.com>;
抄送: "C。罗纳尔多"<875713197@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [IDKiro/CBDNet-pytorch] 有关noise level map (#3)




合成的数据集是会返回noise map的，但是真实数据集我只能相减，可能我没有看到这部分的实现。如果你能指出具体实现方法请告诉我，我抽空进行实现。

**Comment by scutcr7** [comment]
还有一个问题想请教一下，“真实”噪声图不是只有噪声图吗。您通过一个噪声图和原始图的相减操作得到noise map，那么这个原始图是怎么得到的呢
###############################
是从HR图下采样吗？
###############################
不好意思刚才想错了，好愚蠢的问题，哈哈。就是想问一下您测试过具体的效果吗。十分抱歉打扰到您了。




------------------ 原始邮件 ------------------
发件人: "IDKiro"<notifications@github.com>;
发送时间: 2019年8月1日(星期四) 中午1:12
收件人: "IDKiro/CBDNet-pytorch"<CBDNet-pytorch@noreply.github.com>;
抄送: "C。罗纳尔多"<875713197@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [IDKiro/CBDNet-pytorch] 有关noise level map (#3)




合成的数据集是会返回noise map的，但是真实数据集我只能相减，可能我没有看到这部分的实现。如果你能指出具体实现方法请告诉我，我抽空进行实现。

**Comment by IDKiro** [comment]
试了，但是RENOIR这个数据集质量一般，在DND上提高的结果不好，比论文中还低。
混合训练效果稍微好一点。
关于数据集，我推荐你可以看看SSID，也是有noisy和ground truth的。
