### ISSUE TITLE
有关loss

### ISSUE THREAD

**Issue by scutcr7** [IDKiro/CBDNet-pytorch#4]
想问一下您训练时候loss一直是很小吗，我刚开始只有0.00几

**Comment by IDKiro** [comment]
请自己实验，可以尝试下估计loss，l2loss部分是很容易算的，那么正则项绝对比主要的l2loss小，那么大致loss也可以估计出。
刚开始训练的loss和初始化有关系，你要是想体验从很大的loss下降，那就写好初始化方法
