### ISSUE TITLE
Cuda: Out of memory

### ISSUE THREAD

**Issue by HaiTMai** [IDKiro/CBDNet-pytorch#7]
After running the command: 
**python test.py --ckpt synthetic**

I got the error (I am using GTX Titan X)
**RuntimeError: CUDA out of memory. Tried to allocate 1.92 GiB (GPU 0; 11.92 GiB total capacity; 10.85 GiB already allocated; 56.62 MiB free; 128.66 MiB cached).**

Could you check the issues?

**Comment by IDKiro** [comment]
It is because the size of input image is too big, you can add the '--cpu' option or slice the input image.
I also use RTX2080Ti and 11GB memory is not enough.
I think slice the images is better.
