### ISSUE TITLE
噪声图

### ISSUE THREAD

**Issue by LluLl** [IDKiro/CBDNet-pytorch#9]
你好，请问在复现代码时，你是不是考虑过噪声水平这一内容在真实噪声图上的含义？

**Comment by IDKiro** [comment]
论文并没有讲噪声图的计算方式。
不过原仓库的issue中作者有提及，为 Img * sigma_s + sigma_c 。
我代码中给Img开了根号，感觉这样可能更合理。
在我看来，这只是深监督的一种方式，引导网络去学习估计一张空间上变化的噪声图。
以我的经验，这些添加的正则项并没有关键作用。
你可以上DND数据集的页面看看排名更靠前的算法，可能会有发现。

**Comment by LluLl** [comment]
嗯嗯，谢谢
